/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package licencias.views;

import java.util.List;
import java.util.Vector;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import licencias.Agente;

/**
 *
 * @author martin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LicenciasPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("LicenciasPU").createEntityManager();
        licenciaQuery = java.beans.Beans.isDesignTime() ? null : LicenciasPUEntityManager.createQuery("SELECT l FROM Licencia l");
        licenciaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : licenciaQuery.getResultList();
        agenteQuery = java.beans.Beans.isDesignTime() ? null : LicenciasPUEntityManager.createQuery("SELECT a FROM Agente a");
        agenteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : agenteQuery.getResultList();
        agenteQuery1 = java.beans.Beans.isDesignTime() ? null : LicenciasPUEntityManager.createQuery("SELECT a FROM Agente a");
        agenteList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : agenteQuery1.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_agentes = new javax.swing.JMenuItem();
        menu_licencias = new javax.swing.JMenuItem();
        menu_salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EntityManager entityManager = Persistence.createEntityManagerFactory("LicenciasPU").createEntityManager();
        Query query = entityManager.createNamedQuery("Agente.findAll");
        List<Agente> resultList = query.getResultList();

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        for (Agente a : resultList)
        {
            Vector<Object> vector = new Vector<Object>();
            vector.add(a.getDni());
            vector.add(a.getApellido());
            vector.add(a.getNombre());
            vector.add(a.getFechaIngreso());
            data.add(vector);
        }

        Vector<String> columnNames = new Vector<String>();

        columnNames.add("DNI");
        columnNames.add("Apellido");
        columnNames.add("Nombre");
        columnNames.add("Fecha de ingreso");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            data,
            columnNames
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("Archivo");

        menu_agentes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menu_agentes.setText("Agentes");
        jMenu1.add(menu_agentes);

        menu_licencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menu_licencias.setText("Licencias");
        jMenu1.add(menu_licencias);

        menu_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_salir.setText("Salir");
        menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_salirActionPerformed(evt);
            }
        });
        jMenu1.add(menu_salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_salirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager LicenciasPUEntityManager;
    private java.util.List<licencias.Agente> agenteList;
    private java.util.List<licencias.Agente> agenteList1;
    private javax.persistence.Query agenteQuery;
    private javax.persistence.Query agenteQuery1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<licencias.Licencia> licenciaList;
    private javax.persistence.Query licenciaQuery;
    private javax.swing.JMenuItem menu_agentes;
    private javax.swing.JMenuItem menu_licencias;
    private javax.swing.JMenuItem menu_salir;
    // End of variables declaration//GEN-END:variables
}
